lastpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('movie_review/<int:movie_code>/review_create', views.review_create, name='review_create'),
    path('movie_review/<int:movie_code>', views.movie_review, name="movie_review"),
    path('movie_list/<int:date_pk>/', views.movie_list, name="movie_list"),
    path('', views.index, name="index"),
]

movies/models.py
from django.db import models
from django.conf import settings
# MakeDB모델을 거쳐서 movie.csv -> 네이버API -> (Django MakeDB모델) -> DB
class Movie(models.Model):
    # 필요한 정보 : rank, 국문 title, 영문 title, description, poster_url, naver_movie_url, -> csv에서부터 db를 만들기 위해 필요한 필드
    # range_rank = models.CharField(max_length=30)
    # showRange = models.CharField(max_length=30)
    start_date = models.IntegerField()
    end_date = models.IntegerField()
    rank = models.IntegerField()
    poster_url = models.CharField(max_length=200)
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=100)
    actor = models.CharField(max_length=100)
    movie_code = models.CharField(max_length=100)
    naver_movie_url = models.CharField(max_length=100)
    description = models.TextField()
    clicked_users = models.ManyToManyField(  # movie.clicked_users.all()  =>  해당 영화를 클릭한 모든 유저를 불러오는 방법
        settings.AUTH_USER_MODEL,
        # user.clicked_movies.all()  =>  해당 유저가 클릭만 모든 영화를 불러오는 방법
        related_name='clicked_movies'
    )
class Review(models.Model):
    content = models.CharField(max_length=50)
    score = models.IntegerField()
    # 사용자 입장에서 내가 작성한 댓글들에 접근할 때 => user.reviews.all()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='reviews', on_delete=models.CASCADE)
    # 영화 입장에서 나한테 달린 댓글들에 접근할 때 => movie.reviews.all()
    movie = models.ForeignKey(
        Movie, related_name='reviews', on_delete=models.CASCADE)
    class Meta:
        ordering = ('-pk', )
class SearchedDate(models.Model):
    month = models.CharField(max_length=2)
    day = models.CharField(max_length=2)
    # 사용자 입장에서 내가 검색한 모든 날짜 접근 => user.searched_dates.all()
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='searched_dates', on_delete=models.CASCADE)

movies/forms.py
from django import forms
from .models import Review, SearchedDate


class ReviewForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.fields['score'].widget.attrs['max'] = 5
        self.fields['score'].widget.attrs['min'] = 1
        self.fields['content'].widget.attrs['placeholder'] = '댓글을 입력하세요.'
        self.fields['content'].widget.attrs['size'] = 60
        self.fields['score'].widget.attrs['size'] = 10

    class Meta:
        model = Review
        fields = ['content', 'score', ]


class SearchedDateForm(forms.ModelForm):

    class Meta:
        model = SearchedDate
        fields = ['month', 'day', ]

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_GET
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from .models import Movie, Review, SearchedDate
from .forms import ReviewForm, SearchedDateForm
from decouple import config
import csv


def index(request):
    # 로그인이 되어있을 경우에
    if request.user.is_authenticated:
        user = request.user
        searched_dates = SearchedDate.objects.filter(user_id=user.id)
        clicked_movies = user.clicked_movies.all()

        if request.method == 'POST':
            month = request.POST.get('month')
            day = request.POST.get('day')
            last_dates = SearchedDate.objects.filter(user_id=user.id)

            # 기존 검색해 본 날짜를 돌면서, 중복된 검색 날짜가 있으면 바로 그 날짜를 검색하게 한다. 
            for date in last_dates:
                if date.month == month and date.day == day:
                    return redirect('movies:movie_list', date.pk)    

            date = SearchedDate()
            date.month = month
            date.day = day
            date.user = request.user
            date.save()
            
            return redirect('movies:movie_list', date.pk)
        else:  # GET 요청
            dateform = SearchedDateForm()
        context = {
            'clicked_movies': clicked_movies,
            'searched_dates': searched_dates,
            'dateform': dateform,
            'user': user,
        }
        return render(request, 'movies/index.html', context)
    # 로그인 X 유저일 경우 아예 아무 것도 못 함
    else:
        dateform = SearchedDateForm()
        return render(request, 'movies/index.html', {'dateform': dateform})


def movie_list(request, date_pk):
    user = request.user
    clicked_movies = user.clicked_movies.all()
    searched_dates = SearchedDate.objects.filter(user_id=user.id)
    # # date정보를 가져옴 (01/23)
    date = get_object_or_404(SearchedDate, pk=date_pk)
    
    date18 = 20180000 + int(date.month) * 100 + int(date.day)
    date17 = 20170000 + int(date.month) * 100 + int(date.day)
    date16 = 20160000 + int(date.month) * 100 + int(date.day)
    date15 = 20150000 + int(date.month) * 100 + int(date.day)
    date14 = 20140000 + int(date.month) * 100 + int(date.day)
    date13 = 20130000 + int(date.month) * 100 + int(date.day)
    date12 = 20120000 + int(date.month) * 100 + int(date.day)
    date11 = 20110000 + int(date.month) * 100 + int(date.day)
    date10 = 20100000 + int(date.month) * 100 + int(date.day)
    date09 = 20090000 + int(date.month) * 100 + int(date.day)
    date08 = 20080000 + int(date.month) * 100 + int(date.day)
    date07 = 20070000 + int(date.month) * 100 + int(date.day)
    date06 = 20060000 + int(date.month) * 100 + int(date.day)
    date05 = 20050000 + int(date.month) * 100 + int(date.day)
    date04 = 20040000 + int(date.month) * 100 + int(date.day)
    
    movies18 = Movie.objects.filter(
        start_date__lte=date18,
        end_date__gte=date18,
    )
    movies17 = Movie.objects.filter(
        start_date__lte=date17,
        end_date__gte=date17,
    )
    movies16 = Movie.objects.filter(
        start_date__lte=date16,
        end_date__gte=date16,
    )
    movies15 = Movie.objects.filter(
        start_date__lte=date15,
        end_date__gte=date15,
    )
    movies14 = Movie.objects.filter(
        start_date__lte=date14,
        end_date__gte=date14,
    )
    movies13 = Movie.objects.filter(
        start_date__lte=date13,
        end_date__gte=date13,
    )
    movies12 = Movie.objects.filter(
        start_date__lte=date12,
        end_date__gte=date12,
    )
    movies11 = Movie.objects.filter(
        start_date__lte=date11,
        end_date__gte=date11,
    )
    movies10 = Movie.objects.filter(
        start_date__lte=date10,
        end_date__gte=date10,
    )
    movies09 = Movie.objects.filter(
        start_date__lte=date09,
        end_date__gte=date09,
    )
    movies08 = Movie.objects.filter(
        start_date__lte=date08,
        end_date__gte=date08,
    )
    movies07 = Movie.objects.filter(
        start_date__lte=date07,
        end_date__gte=date07,
    )
    movies06 = Movie.objects.filter(
        start_date__lte=date06,
        end_date__gte=date06,
    )
    movies05 = Movie.objects.filter(
        start_date__lte=date05,
        end_date__gte=date05,
    )
    movies04 = Movie.objects.filter(
        start_date__lte=date04,
        end_date__gte=date04,
    )

    context = {
        'date': date,
        'movies18': movies18,
        'movies17': movies17,
        'movies16': movies16,
        'movies15': movies15,
        'movies14': movies14,
        'movies13': movies13,
        'movies12': movies12,
        'movies11': movies11,
        'movies10': movies10,
        'movies09': movies09,
        'movies08': movies08,
        'movies07': movies07,
        'movies06': movies06,
        'movies05': movies05,
        'movies04': movies04,
        'searched_dates': searched_dates,
        'clicked_movies': clicked_movies,
    }
    return render(request, 'movies/movie_list.html', context)


def movie_review(request, movie_code):
    user = request.user
    
    # 내가 클릭한 영화 (현재)
    movie = Movie.objects.filter(movie_code=movie_code).first()

    # 내(user)가 기존에 클릭해 본 영화들 
    clicked_movies = user.clicked_movies.all()

    flag = False
    for last_movie in clicked_movies:
        if last_movie.title == movie.title:
            flag = True

    if flag == False: # 지금 클릭한 영화가 처음 클릭한 영화인 경우
       user.clicked_movies.add(movie)

    searched_dates = SearchedDate.objects.filter(user_id=user.id)    
    clicked_movies = user.clicked_movies.all()
    
    reviews = movie.reviews.all()
    review_form = ReviewForm()

    context = {
        'movie': movie,
        'reviews': reviews,
        'review_form': review_form,
        'searched_dates': searched_dates,
        'clicked_movies': clicked_movies,
    }
    return render(request, 'movies/movie_review.html', context)


def review_create(request, movie_code):
    movie = Movie.objects.filter(movie_code=movie_code).first()
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.movie_id = movie.id
            review.user_id = request.user.id
            review.save()
        
        return redirect('movies:movie_review', movie_code)

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block style %}
.page-content {
  text-align: center;
}

.page-content h1 {
  text-size: 200px;
}

input[type=text] {
  text-align: center;
  background: transparent;
  font-family: 'Nanum Pen Script', cursive;
  border: none;
  border-bottom: 0.5px solid #42195f;
}

form {
  font-family: 'Nanum Pen Script', cursive;
  {% comment %} font-family: 'Nanum Myeongjo', serif; {% endcomment %}
  font-size: 35px;
  font-weight: bold;
  color: #c6bfca;
}

form > button {
  background: transparent;
  color: #c6bfca;
  border: none;
  border-bottom: 0.5px solid #42195f;
}

.story {
  margin-top: 20px;
}

.story > p {
  text-align: center-left;
  font-family: 'Nanum Gothic', serif;
  font-size: 15px;
  color: #c6bfca;
}

{% endblock style %}

{% block title %}그날의 박스오피스{% endblock title %}

{% block container %}
  <div class="page-content">
  {% comment %} <h1>그날의 박스오피스</h1> {% endcomment %}
  <form method="POST">
    {% csrf_token %}
    {% comment %} {{ dateform.month }} 월 {{ dateform.day }} 일 {% endcomment %}
    <input size="1.2" type="text" name="month">월
    <input size="1.2" type="text" name="day">일의 영화 순위
    <button type="submit">보러가기</button>
  </form>
  <div class="story">
    <p>{{ user.username }} 님의 특별한 날을 입력해 보세요</p> 
    <p>2018년에서 2004년까지</p>  
    <p>그날의 추억을 간직한 박스오피스를 보여드립니다 </p>
  </div>

  </div>
{% endblock container %}

{% comment %} sidebar에 날짜 넣는 부분 {% endcomment %}
{% block date %}

{% for date in searched_dates %}
  <a href="{% url 'movies:movie_list' date.id %}" class="sidebar_date">{{ date.month }}월 {{ date.day }}일<br></a> 
{% endfor %}

{% endblock date %}


{% comment %} sidebar에 영화 넣는 부분 {% endcomment %}
{% block sidemovie %} 

{% for movie in clicked_movies %}
  <img src="{{ movie.poster_url }}" class="sidebar_card"><br>
  <div class="card-body">
    <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}</a><br></h4>
  </div>
  
{% endfor %}

{% endblock sidemovie %}

movies/templates/movies/movie_list.html
{% extends 'base.html' %}

{% block title %}{{ date.month }}월 {{ date.day }}일의 영화 순위{% endblock title %}

{% block style %}

.title h1 {
  font-family: 'Nanum Pen Script', cursive;
  text-size: 40px;
}

.container p {
  font-family: 'Nanum Pen Script', cursive;
}
{% endblock style %}

{% block logo %}
<div class="title">
  <h1>{{ date.month }}월 {{ date.day }}일의 영화 순위</h1>
</div>
{% endblock logo %}
{% block body %}
<div class="container">
  <p><h3>2018년 Top4</h3></p>
  {% for movie in movies18 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <p><h3>2017년 Top4</h3></p>
  {% for movie in movies17 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <p><h3>2016년 Top4</h3></p>
  {% for movie in movies16 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <p><h3>2015년 Top4</h3></p>
  {% for movie in movies15 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <p><h3>2014년 Top4</h3></p>
  {% for movie in movies14 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <p><h3>2013년 Top4</h3></p>
  {% for movie in movies13 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <p><h3>2012년 Top4</h3></p>
  {% for movie in movies12 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <p><h3>2011년 Top4</h3></p>
  {% for movie in movies11 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <p><h3>2010년 Top4</h3></p>
  {% for movie in movies10 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <p><h3>2009년 Top4</h3></p>
  {% for movie in movies09 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <p><h3>2008년 Top4</h3></p>
  {% for movie in movies08 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <p><h3>2007년 Top4</h3></p>
  {% for movie in movies07 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <p><h3>2006년 Top4</h3></p>
  {% for movie in movies06 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <p><h3>2005년 Top4</h3></p>
  {% for movie in movies05 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <p><h3>2004년 Top4</h3></p>
  {% for movie in movies04 %}
  {% if movie.rank <= 4 %}
  <div class="b-blcok col-xl-3 col-lg-3 col-md-3 col-3">
    <div class="card">
      <img src="{{ movie.poster_url }}" class="card-img-top">
      <div class="card-body">
        <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}<br></a><br>
        </h4>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
{% endblock body %}


{% comment %} sidebar에 날짜 넣는 부분 {% endcomment %}
{% block date %}

{% for date in searched_dates %}
  <a href="{% url 'movies:movie_list' date.id %}" class="sidebar_date">{{ date.month }}월 {{ date.day }}일<br></a> 
{% endfor %}

{% endblock date %}


{% comment %} sidebar에 영화 넣는 부분 {% endcomment %}
{% block sidemovie %} 

{% for movie in clicked_movies %}
  <img src="{{ movie.poster_url }}" class="sidebar_card"><br>
  <div class="card-body">
    <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}</a><br></h4>
  </div>
  
{% endfor %}

{% endblock sidemovie %}

movies/templates/movies/movie_review.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ movie.title }} 상세보기ㄴ{% endblock title %}

{% block container %}
  <hr>
  <h1>{{ movie.title }}</h1>
  <h3 style="color:darkgray">({{ movie.subtitle }})</h3>
  <a href="{{ movie.naver_movie_url }}"><img class="naver_logo" src="{% static 'naver_logo.png' %}" width=40px height=40px><br></a>
  <div class="actor">
  {{ movie.actor }}
  <hr>
  </div>
  <img src="{{ movie.poster_url }}" alt="image" style="width: 100%"><br>
  <br>
  <div class="movie_description">
    {{ movie.description }}
  </div>
  
  {% comment %} 리뷰 작성 {% endcomment %}
  <br>
  <br>
  <hr>
  <h3>Review</h3> 
  <ul>
    {% for review in reviews %}
      <div class="movie_review">
      <li>{{ review.content }}
      {% if review.score == 1 %}
      ⭐
      {% endif %}
      {% if review.score == 2  %}
      ⭐⭐
      {% endif %}
      {% if review.score == 3  %}
      ⭐⭐⭐
      {% endif %}
      {% if review.score == 4  %}
      ⭐⭐⭐⭐
      {% endif %}
      {% if review.score == 5  %}
      ⭐⭐⭐⭐⭐
      {% endif %}
      </li><br>
      </div>
    {% endfor %}
  </ul>
  <hr>
  <form action="{% url 'movies:review_create' movie.movie_code %}"method="POST" style="width:100%">
    {% csrf_token %}
    {{ review_form }}
    <button type="submit">작성</button>
  </form>
  

{% endblock container %}



{% comment %} sidebar에 날짜 넣는 부분 {% endcomment %}
{% block date %}

{% for date in searched_dates %}
  <a href="{% url 'movies:movie_list' date.id %}" class="sidebar_date">{{ date.month }}월 {{ date.day }}일<br></a> 
{% endfor %}

{% endblock date %} 


{% comment %} sidebar에 영화 넣는 부분 {% endcomment %}
{% block sidemovie %}

{% for movie in clicked_movies %}
  
  <img src="{{ movie.poster_url }}" class="sidebar_card"><br>
  <div class="card-body">
    <h4 class="card-title"><a href="{% url 'movies:movie_review' movie.movie_code %}">{{ movie.title }}</a><br></h4>
  </div>
  
{% endfor %}

{% endblock sidemovie %}