accounts/urls.py
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

lastpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('movie_review/<int:movie_code>/review_create', views.review_create, name='review_create'),
    path('movie_review/<int:movie_code>', views.movie_review, name="movie_review"),
    path('movie_list/<int:date_pk>/', views.movie_list, name="movie_list"),
    path('', views.index, name="index"),
]

movies/models.py
from django.db import models
from django.conf import settings
# MakeDB모델을 거쳐서 movie.csv -> 네이버API -> (Django MakeDB모델) -> DB
class Movie(models.Model):
    # 필요한 정보 : rank, 국문 title, 영문 title, description, poster_url, naver_movie_url, -> csv에서부터 db를 만들기 위해 필요한 필드
    # range_rank = models.CharField(max_length=30)
    # showRange = models.CharField(max_length=30)
    start_date = models.IntegerField()
    end_date = models.IntegerField()
    rank = models.IntegerField()
    poster_url = models.CharField(max_length=200)
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=100)
    actor = models.CharField(max_length=100)
    movie_code = models.CharField(max_length=100)
    naver_movie_url = models.CharField(max_length=100)
    description = models.TextField()
    clicked_users = models.ManyToManyField(  # movie.clicked_users.all()  =>  해당 영화를 클릭한 모든 유저를 불러오는 방법
        settings.AUTH_USER_MODEL,
        # user.clicked_movies.all()  =>  해당 유저가 클릭만 모든 영화를 불러오는 방법
        related_name='clicked_movies'
    )
class Review(models.Model):
    content = models.CharField(max_length=50)
    score = models.IntegerField()
    # 사용자 입장에서 내가 작성한 댓글들에 접근할 때 => user.reviews.all()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='reviews', on_delete=models.CASCADE)
    # 영화 입장에서 나한테 달린 댓글들에 접근할 때 => movie.reviews.all()
    movie = models.ForeignKey(
        Movie, related_name='reviews', on_delete=models.CASCADE)
    class Meta:
        ordering = ('-pk', )
class SearchedDate(models.Model):
    month = models.CharField(max_length=2)
    day = models.CharField(max_length=2)
    # 사용자 입장에서 내가 검색한 모든 날짜 접근 => user.searched_dates.all()
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='searched_dates', on_delete=models.CASCADE)

lastpjt/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <title>{% block title %}{% endblock title %}</title>
  <style>
    body {
      background-image: url(https://i.redd.it/vcu684cde8y01.jpg);
      background-size: cover;
      background-position: center;
      background-repeat: no-repeat;
      background-attachment: fixed;
      position: relative;
      overflow-x: hidden;
    }

    h3, h2, h1 {
      font-family: 'Nanum Gothic', sans-serif;
      font-weight: bold;
      display: inline-block;
      color: #c6bfca;
      margin-top: 1px;
    }

    .actor {
      font-family: 'Nanum Gothic', sans-serif;
      font-weight: bold;
      color: #c6bfca;
    }

    label {
      color: #c6bfca;
    }
    
    body,
    html {
      height: 100%;
    }

    #id_content {
      margin-right: 30px;
      margin-left: 10px;
    }
    
    .card-img-top {
      width: 200px;
      height: 300px;
      display: inline-block;
      margin-left: 28px;
    }

    .naver_logo {
      float: right;
      margin-top: 12px;
    }

    .sidebar_card {
      width: 110px;
      height: 158px;
      display: inline-block;
      margin-left: 55px;
    }

    .sidebar_date {
      margin-left: 80px;
    }

    #id_score {
      margin-right: 30px;
      margin-left: 10px;
    }

    .home {
      position:fixed;
      right: 20px;
      top:20px;
    }

    .movie_description {
      background-color: #ffffff24;
      color: #c7c3c7;
      text-weight: bold;
      border-radius: 0.6em;
    }

    .movie_review {
      background-color: #ffffff24;
      color: #c7c3c7;
      text-weight: bold;
    }

    .card-title {
      display: inline-block;
      text-align: center;
    }

    .card {
      text-align: center;
      margin-right: 0;
    }

    .card-body {
      text-align: center;
      margin-right: 0;
    }
    
    .nav .open>a,
    .nav .open>a:hover,
    .nav .open>a:focus {
      background-color: transparent;
    }

    /*-------------------------------*/
    /*           Wrappers            */
    /*-------------------------------*/

    .title {
      color: #b9aac1;
      text-align: center;
      font-family: 'Nanum Gothic', sans-serif;
      font-weight: bold;
      font-size: 5.5rem;
    }

    #wrapper {
      padding-left: 0;
      -webkit-transition: all 0.5s ease;
      -moz-transition: all 0.5s ease;
      -o-transition: all 0.5s ease;
      transition: all 0.5s ease;
    }

    #wrapper.toggled {
      padding-left: 220px;
    }

    #sidebar-wrapper {
      /* z-index는 태그들이 겹칠 때 누가 더 위로 올라가는지를 결정하는 속성, 기본값은 0 */
      z-index: 1000;
      /* z축 상의 위치를 나타내며, 정수값(음수, 양수). 높은 번호를 가진 레이어는 낮은 번호를 가진 레이어 위에 렌더링된다 */
      left: 220px;
      width: 0;
      height: 100%;
      margin-left: -220px;
      overflow-y: auto;
      /* 본문에 표시되는 내용에 따라 세로 스크롤이 생긴다. */
      overflow-x: hidden;
      /* 부모요소의 범위를 넘어가는 자식요소의 부분은 보이지 않도록 처리 */
      background: darkgray;
      -webkit-transition: all 0.5s ease;
      /* CSS 속성을 변경할 때 애니메이션 속도를 조절하는 방법을 제공 */
      -moz-transition: all 0.5s ease;
      -o-transition: all 0.5s ease;
      transition: all 0.5s ease;
    }

    #sidebar-wrapper::-webkit-scrollbar {
      display: none;
      /* 보이지 않음 */
    }

    #wrapper.toggled #sidebar-wrapper {
      width: 220px;
    }

    #page-content-wrapper {
      width: 100%;
      padding-top: 70px;
    }

    #wrapper.toggled #page-content-wrapper {
      position: absolute;
      /* 가장 가까운 곳에 위치한 조상 엘리먼트에 상대적으로 위치가 지정된다. */
      /* relative가 static인 상태를 기준으로 주어진 픽셀만큼 움직였다면, */
      /* absolute는 position: static 속성을 가지고 있지 않은 부모를 기준으로 움직인다. */
      /* 만약 부모 중에 포지션이 relative, absolute, fixed인 태그가 없다면 가장 위의 태그(body)가 기준이 된다. */
      margin-right: -220px;
    }

    /*-------------------------------*/
    /*     Sidebar nav styles        */
    /*-------------------------------*/
    .sidebar-nav {
      position: absolute;
      top: 0;
      width: 220px;
      margin: 0;
      padding: 0;
      list-style: none;
    }

    .sidebar-nav li {
      position: relative;
      line-height: 20px;
      display: inline-block;
      width: 100%;
    }

    .sidebar-nav li:before {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      z-index: -1;
      height: 100%;
      width: 3px;
      background-color: #1c1c1c;
      -webkit-transition: width .2s ease-in;
      -moz-transition: width .2s ease-in;
      -ms-transition: width .2s ease-in;
      transition: width .2s ease-in;
    }

    .sidebar-nav li:first-child a {
      color: #fff;
      background-color: #1a1a1a;
    }

    .sidebar-nav li:before {
      background-color: #D8D8D8;
    }

    .sidebar-nav li:hover:before,
    .sidebar-nav li.open:hover:before {
      width: 100%;
      -webkit-transition: width .2s ease-in;
      -moz-transition: width .2s ease-in;
      -ms-transition: width .2s ease-in;
      transition: width .2s ease-in;
    }

    .sidebar-nav li a {
      display: block;
      /* 요소를 block 요소처럼 표시한다. 요소 앞뒤로 줄바꿈 된다. */
      color: #ddd;
      text-decoration: none;
      /* 선을 만들지 않는다. */
      padding: 10px 15px 10px 30px;
    }

    .sidebar-nav li a:hover,
    .sidebar-nav li a:active,
    .sidebar-nav li a:focus,
    .sidebar-nav li.open a:hover,
    .sidebar-nav li.open a:active,
    .sidebar-nav li.open a:focus {
      color: #fff;
      text-decoration: none;
      background-color: transparent;
    }

    .sidebar-nav>.sidebar-brand {
      height: 45px;
      font-size: 16px;
      line-height: 24px;
    }

    .sidebar-nav .dropdown-menu {
      position: relative;
      width: 100%;
      padding: 0;
      margin: 0;
      border-radius: 0;
      border: none;
      background-color: #222;
      box-shadow: none;
    }

    /*-------------------------------*/
    /*       Link2me-Cross         */
    /*-------------------------------*/
    .link2me {
      position: fixed;
      /* fixed: 스크롤과 상관없이 항상 문서 최 좌측상단을 기준으로 좌표를 고정 */
      top: 20px;
      z-index: 999;
      /* z-index는 태그들이 겹칠 때 누가 더 위로 올라가는지를 결정하는 속성, 기본값은 0 */
      display: block;
      /* 요소를 block 요소처럼 표시한다. 요소 앞뒤로 줄바꿈 된다. */
      width: 32px;
      height: 32px;
      margin-left: 15px;
      background: transparent;
      border: none;
    }

    .link2me:hover,
    .link2me:focus,
    .link2me:active {
      outline: none;
    }

    .link2me.is-closed:before {
      content: '';
      display: block;
      width: 100px;
      font-size: 14px;
      color: #fff;
      line-height: 32px;
      text-align: center;
      opacity: 0;
      -webkit-transform: translate3d(0, 0, 0);
      -webkit-transition: all .35s ease-in-out;
    }

    .link2me.is-closed:hover:before {
      opacity: 1;
      display: block;
      -webkit-transform: translate3d(-100px, 0, 0);
      -webkit-transition: all .35s ease-in-out;
    }

    .link2me.is-closed .hamb-top,
    .link2me.is-closed .hamb-middle,
    .link2me.is-closed .hamb-bottom,
    .link2me.is-open .hamb-top,
    .link2me.is-open .hamb-middle,
    .link2me.is-open .hamb-bottom {
      position: absolute;
      left: 0;
      height: 4px;
      width: 100%;
    }

    .link2me.is-closed .hamb-top,
    .link2me.is-closed .hamb-middle,
    .link2me.is-closed .hamb-bottom {
      background-color: #c6bfca;
    }

    .link2me.is-closed .hamb-top {
      top: 5px;
      -webkit-transition: all .35s ease-in-out;
    }

    .link2me.is-closed .hamb-middle {
      top: 50%;
      margin-top: -2px;
    }

    .link2me.is-closed .hamb-bottom {
      bottom: 5px;
      -webkit-transition: all .35s ease-in-out;
    }

    .link2me.is-closed:hover .hamb-top {
      top: 0;
      -webkit-transition: all .35s ease-in-out;
    }

    .link2me.is-closed:hover .hamb-bottom {
      bottom: 0;
      -webkit-transition: all .35s ease-in-out;
    }

    .link2me.is-open .hamb-top,
    .link2me.is-open .hamb-middle,
    .link2me.is-open .hamb-bottom {
      background-color: #c6bfca;
    }

    .link2me.is-open .hamb-top,
    .link2me.is-open .hamb-bottom {
      top: 50%;
      margin-top: -2px;
    }

    .link2me.is-open .hamb-top {
      -webkit-transform: rotate(45deg);
      -webkit-transition: -webkit-transform .2s cubic-bezier(.73, 1, .28, .08);
    }

    .link2me.is-open .hamb-middle {
      display: none;
    }

    .link2me.is-open .hamb-bottom {
      -webkit-transform: rotate(-45deg);
      -webkit-transition: -webkit-transform .2s cubic-bezier(.73, 1, .28, .08);
    }

    .link2me.is-open:before {
      content: '';
      display: block;
      width: 100px;
      font-size: 14px;
      color: #fff;
      line-height: 32px;
      text-align: center;
      opacity: 0;
      -webkit-transform: translate3d(0, 0, 0);
      -webkit-transition: all .35s ease-in-out;
    }

    .link2me.is-open:hover:before {
      opacity: 1;
      display: block;
      -webkit-transform: translate3d(-100px, 0, 0);
      -webkit-transition: all .35s ease-in-out;
    }

    /*-------------------------------*/
    /*            Overlay            */
    /*-------------------------------*/
    .overlay {
      position: fixed;
      /* fixed: 스크롤과 상관없이 항상 문서 최 좌측상단을 기준으로 좌표를 고정 */
      display: none;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background-color: rgba(0, 0, 0, .4);
      z-index: 1;
    }

    .logout {
      margin: 7px 0 0 10px;
    }

    {% block style %}
    {% endblock style %}

  </style>
  <link href="https://fonts.googleapis.com/css?family=Do+Hyeon|Nanum+Gothic|Nanum+Myeongjo|Nanum+Pen+Script|Noto+Serif+KR&display=swap" rel="stylesheet">
</head>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <script>
    $(document).ready(function () {
      var trigger = $('.link2me'),
        overlay = $('.overlay'),
        isClosed = false;
      trigger.click(function () {
        link2me_cross();
      });
      function link2me_cross() {
        if (isClosed == true) {
          overlay.hide();
          trigger.removeClass('is-open');
          trigger.addClass('is-closed');
          isClosed = false;
        } else {
          overlay.show();
          trigger.removeClass('is-closed');
          trigger.addClass('is-open');
          isClosed = true;
        }
      }
      $('[data-toggle="offcanvas"]').click(function () {
        $('#wrapper').toggleClass('toggled');
      });
    });
  </script>
  </body>
  {% comment %} navbar 시험용 {% endcomment %}

  <div id="wrapper">
    <div class="overlay"></div>
    <!-- Sidebar 숨김으로 보였다 보이지 않았다 하는 부분 -->
    <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
      <ul class="nav sidebar-nav">
        {% if user.is_authenticated %}
        <p class="logout">
          <a href="{% url 'accounts:logout' %}">로그아웃</a>
        </p>
        {% comment %} 사진, 이름을 보여주는 부분 {% endcomment %}
        <div class="text-center">
          <img src="{% static '프로필.jpg' %}" class="img-circle" width=100px height=100px><br>
          <span>{{ user.username }}</span><br>
        </div>
        {% comment %} 클릭한 영화, 날짜를 보여주는 부분 {% endcomment %}
        <h4>날짜</h4>
        {% block date %}
        {% endblock date %}
        
        <h4>영화</h4>
        {% block sidemovie %}
        {% endblock sidemovie %}
        
        {% else %}
        <p class="logout">
          <a href="{% url 'accounts:login' %}">로그인</a>
          <a href="{% url 'accounts:signup' %}">회원가입</a>
        </p>
        {% endif %}
      </ul>
    </nav>
    <!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <div class="home">
      <a href="{% url 'movies:index' %}"><span class="glyphicon glyphicon-home fa-lg"></span></a>
    </div>
    <div id="page-content-wrapper">
      <button type="button" class="link2me is-closed" data-toggle="offcanvas">
        <span class="hamb-top"></span>
        <span class="hamb-middle"></span>
        <span class="hamb-bottom"></span>
      </button>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2" style="margin-left: auto">
            <h1>{% block logo %}{% endblock logo %}</h1>
            {% block body %}
            {% endblock body %}
          </div>
          <div class="col-lg-8 col-lg-offset-2">
            {% block container %}
            {% endblock container %}
          </div>
        </div>
      </div>
    </div>
    <!-- /#page-content-wrapper -->
  </div>
  <!-- /#wrapper -->
  </body>

</html>